#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'interQuartile' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY values
#  2. INTEGER_ARRAY freqs
#

def interQuartile(values, freqs):
    l1=[]
    for i in range(n):
        for j in range(freqs[i]):
            l1.append(values[i])
    p=len(l1)
    l1.sort()
    l2=[]
    l3=[]
    if(p%2!=0):
        l2=l1[0:(p-1)//2]
        l3=l1[(p+1)//(2):p]
    else:
        l2=l1[0:p//2]
        l3=l1[p//2:p]
    s=len(l2)
    if(s%2==0):
        Q1=(l2[(s//2)-1] + l2[s//2])/2
        Q3=(l3[(s//2)-1] + l3[s//2])/2
    else:
        Q1=l2[(s-1)//2]
        Q3=l3[(s-1)//2]
    print(format(Q3-Q1,".1f"))

    
    

if __name__ == '__main__':
    n = int(raw_input().strip())

    values = map(int, raw_input().rstrip().split())

    freqs = map(int, raw_input().rstrip().split())

    interQuartile(values, freqs)
