#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'weightedMean' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY X
#  2. INTEGER_ARRAY W
#

def weightedMean(X, W):
    s=len(X)
    l1=[]
    for i in range(s):
        p=X[i]*W[i]
        l1.append(p)
    Sum1=sum(l1)
    Sum2=sum(W)
    Wmean=(Sum1)/(Sum2)
    print(format(Wmean,".1f"))
        

if __name__ == '__main__':
    n = int(input().strip())

    vals = list(map(int, input().rstrip().split()))

    weights = list(map(int, input().rstrip().split()))

    weightedMean(vals, weights)
